
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
@BASEURL = http://localhost:8085/api/evaluation-tool



## languages
### get all
get {{BASEURL}}/survey-languages


## localizations
### get all
get {{BASEURL}}/survey-localizations

## surveys
### get all
get {{BASEURL}}/surveys


## steps
### get all
get {{BASEURL}}/survey-steps

## elements
### get all
get {{BASEURL}}/survey-elements

## step types
### get all
get {{BASEURL}}/survey-step-types

## step results
### get all
get {{BASEURL}}/survey-step-results

## step result assets
### get all
get {{BASEURL}}/survey-step-result-assets

## steps of one particular survey
### get all
get {{BASEURL}}/surveys/1/survey-steps